# Generated by Django 5.2.4 on 2025-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_order_issue_reported_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('bike', 'Bike')], default='car', max_length=10),
        ),
    ]
